Fix bug in /api/v1/users/is-unsubscribed response generation
The endpoint never correctly generated the response, and it needed
to be altered to be valid JSON. Since the endpoint never worked
correctly, we mark this as bugfix and not a breaking change.

The error we refer to was:

  TypeError: Argument 2 passed to JsonApiResponse::__construct()
  must be of the type array, bool given.

remp/crm#1100